version: '3'

services:
  neo4j_etl:
    build:
      context: ./neo4j_etl
    env_file:
      - .env  

  chatbot_api:
    build:
      context: ./chatbot_api
    env_file:
      - .env  
    depends_on:
      - neo4j_etl  
    ports:
      - "8000:8000"  
